language: cpp
compiler: gcc
sudo: require
dist: xenial
  
script:
  - bash -ex linux/appimage.sh

after_success:
  - curl --upload-file Imager*.AppImage https://transfer.sh/Imager-git.$(git rev-parse --short HEAD)-x86_64.AppImage
